theme: jekyll-theme-cayman
title: Fisayo Ajayi | Portfolio
description: Data Analyst & Analytics Engineer specializing in predictive financial risk engines, advanced machine learning, and logistics optimization pipelines.
show_downloads: false
google_analytics:
